#!/bin/bash

# setting - docker info
DOCKER_USER_NAME=uvclab
DOCKER_IMAGE_NAME=flexing-mes-server-2.0
DOCKER_IMAGE_TAG={tag}
DOCKER_PROJECT_NAME=mes-dev
DOCKER_CONTAINER_NAME=$DOCKER_IMAGE_NAME-$DOCKER_PROJECT_NAME
DOCKER_PORT=23000
DOCKER_NODE_HTTPS_PORT=23443
DOCKER_HOME=/app
DOCKER_VOLUME=/home/docker/volumes/$DOCKER_CONTAINER_NAME
DOCKER_IMAGE=$DOCKER_USER_NAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

# setting - .env
# nodejs setting
NODE_ENV=development
# NODE_ENV=developmentproduction
NODE_PORT=3030
NODE_HTTPS_PORT=443
LOGGER_LEVEL=debug
EXCLUDE_EVENT_HISTORY=autopin
# LOGGER_LEVEL=info
# access-token setting
ACCESS_TOKEN_EXPIRESIN=10h
# db setting
DB_HOST=10.0.0.7
DB_PORT=25432
DB_DATABASE=$DOCKER_PROJECT_NAME
DB_ID=postgres
DB_PASS=@dbqlTl1
DB_DIALECT=postgres
# mqtt setting
MQTT_HOST=192.168.0.123
MQTT_PORT=1883
MQTT_TOPIC=$DOCKER_PROJECT_NAME/mes
MQTT_WS_PROTOCOL=ws
MQTT_WS_HOST=192.168.0.123
MQTT_WS_PORT=9001
# redis setting
REDIS_HOST=192.168.0.123
REDIS_PORT=6379
REDIS_HEADER=$DOCKER_PROJECT_NAME
# pop url setting ##########
POP_URL=https://mes-demo.flexing.ai/mes-dev
# pms.smart-factory.kr api key ###########
PMS_API_URL=
PMS_API_KEY=

# ssl copy
mkdir -p $DOCKER_VOLUME/ssl
cp /etc/ssl/ssl-flexing.crt $DOCKER_VOLUME/ssl/ssl-flexing.crt
cp /etc/ssl/flexing.ai.key $DOCKER_VOLUME/ssl/flexing.ai.key

# docker run #################################
docker run --name $DOCKER_CONTAINER_NAME \
-p $DOCKER_PORT:$NODE_PORT \
-p $DOCKER_NODE_HTTPS_PORT:$NODE_HTTPS_PORT \
-e NODE_ENV=$NODE_ENV \
-e PORT=$NODE_PORT \
-e NODE_PORT=$NODE_PORT \
-e NODE_HTTPS_PORT=$NODE_HTTPS_PORT \
-e LOGGER_LEVEL=$LOGGER_LEVEL \
-e EXCLUDE_EVENT_HISTORY=$EXCLUDE_EVENT_HISTORY \
-e ACCESS_TOKEN_EXPIRESIN=$ACCESS_TOKEN_EXPIRESIN \
-e DB_HOST=$DB_HOST \
-e DB_PORT=$DB_PORT \
-e DB_DATABASE=$DB_DATABASE \
-e DB_ID=$DB_ID \
-e DB_PASS=$DB_PASS \
-e DB_DIALECT=$DB_DIALECT \
-e MQTT_HOST=$MQTT_HOST \
-e MQTT_PORT=$MQTT_PORT \
-e MQTT_TOPIC=$MQTT_TOPIC \
-e MQTT_WS_PROTOCOL=$MQTT_WS_PROTOCOL \
-e MQTT_WS_HOST=$MQTT_WS_HOST \
-e MQTT_WS_PORT=$MQTT_WS_PORT \
-e REDIS_HOST=$REDIS_HOST \
-e REDIS_PORT=$REDIS_PORT \
-e REDIS_HEADER=$REDIS_HEADER \
-e PROJECT_NAME=$DOCKER_PROJECT_NAME \
-e POP_URL=$POP_URL \
-e PMS_API_URL=$PMS_API_URL \
-e PMS_API_KEY=$PMS_API_KEY \
-v $DOCKER_VOLUME/logs:$DOCKER_HOME/logs \
-v $DOCKER_VOLUME/uploads:$DOCKER_HOME/uploads \
-v $DOCKER_VOLUME/files:$DOCKER_HOME/files \
-v $DOCKER_VOLUME/ssl:$DOCKER_HOME/ssl \
-d \
$DOCKER_IMAGE
