import { UserInsertParams } from '../models/common/user';
import { CommonCodeInsertParams } from '../models/common/commonCode';

// 데이터 초기화를 위한 값들의 모임

// 시스템 관리자
export const initUser: UserInsertParams = {
  companyId: null,
  userid: 'system',
  password: '@dbqlTl1',
  pin: null,
  name: '시스템관리자',
  auth: 'system',
  email: null,
  mobile: null,
  externalCode: null,
  activePin: false,
  active: true,
  partnerId: null,
};

// 공통 코드
export const initCommonCodes: Array<CommonCodeInsertParams> = [
  // JOB_TITLE(직위)
  { code: 'JOB_TITLE', name: '직급', masterCode: 'JOB_TITLE', level: 0, type: 'system', orderby: 0, description: '' },
  { code: 'STAFF', name: '사원', masterCode: 'JOB_TITLE', level: 1, type: 'company', orderby: 1, description: '' },
  {
    code: 'ASSISTANT_MANAGER',
    name: '대리',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  { code: 'MANAGER', name: '과장', masterCode: 'JOB_TITLE', level: 1, type: 'company', orderby: 3, description: '' },
  {
    code: 'DEPUTY_GENERAL_MANAGER',
    name: '차장',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 4,
    description: '',
  },
  {
    code: 'GENERAL_MANAGER',
    name: '부장',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 5,
    description: '',
  },
  { code: 'DIRECTOR', name: '이사', masterCode: 'JOB_TITLE', level: 1, type: 'company', orderby: 6, description: '' },
  {
    code: 'MANAGING_DIRECTOR',
    name: '상무',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 7,
    description: '',
  },
  {
    code: 'EXECUTIVE_VICE_PRESIDENT',
    name: '전무',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 8,
    description: '',
  },
  {
    code: 'VICE_PRESIDENT',
    name: '부사장',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 9,
    description: '',
  },
  { code: 'PRESIDENT', name: '사장', masterCode: 'JOB_TITLE', level: 1, type: 'company', orderby: 10, description: '' },
  {
    code: 'VICE_CHAIRMAN',
    name: '부회장',
    masterCode: 'JOB_TITLE',
    level: 1,
    type: 'company',
    orderby: 11,
    description: '',
  },
  { code: 'CHAIRMAN', name: '회장', masterCode: 'JOB_TITLE', level: 1, type: 'system', orderby: 0, description: '' },
  // JOB_POSITION(직책)
  {
    code: 'JOB_POSITION',
    name: '직책',
    masterCode: 'JOB_POSITION',
    level: 0,
    type: 'system',
    orderby: 1,
    description: '',
  },
  {
    code: 'TEAM_LEADER',
    name: '팀장',
    masterCode: 'JOB_POSITION',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'GROUP_LEADER',
    name: '그룹장',
    masterCode: 'JOB_POSITION',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  {
    code: 'BRANCH_MANAGER',
    name: '지점장',
    masterCode: 'JOB_POSITION',
    level: 1,
    type: 'company',
    orderby: 4,
    description: '',
  },
  { code: 'CEO', name: 'CEO', masterCode: 'JOB_POSITION', level: 1, type: 'company', orderby: 5, description: '' },
  { code: 'CFO', name: 'CFO', masterCode: 'JOB_POSITION', level: 1, type: 'company', orderby: 6, description: '' },
  { code: 'CTO', name: 'CTO', masterCode: 'JOB_POSITION', level: 1, type: 'company', orderby: 7, description: '' },
  { code: 'COO', name: 'COO', masterCode: 'JOB_POSITION', level: 1, type: 'company', orderby: 8, description: '' },
  // JOB_RANK(직급)
  { code: 'JOB_RANK', name: '직급', masterCode: 'JOB_RANK', level: 0, type: 'system', orderby: 0, description: '' },
  {
    code: 'JOB_RANK_1ST',
    name: '1호봉',
    masterCode: 'JOB_RANK',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'JOB_RANK_2ND',
    name: '2호봉',
    masterCode: 'JOB_RANK',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'JOB_RANK_3RD',
    name: '3호봉',
    masterCode: 'JOB_RANK',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  {
    code: 'JOB_RANK_4TH',
    name: '4호봉',
    masterCode: 'JOB_RANK',
    level: 1,
    type: 'company',
    orderby: 4,
    description: '',
  },
  {
    code: 'JOB_RANK_5TH',
    name: '5호봉',
    masterCode: 'JOB_RANK',
    level: 1,
    type: 'company',
    orderby: 5,
    description: '',
  },
  // COMPANY_TYPE(사업장 유형)
  {
    code: 'COMPANY_TYPE',
    name: '사업장 유형',
    masterCode: 'COMPANY_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'MASTER_COMPANY',
    name: '본사 사업장',
    masterCode: 'COMPANY_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '',
  },
  {
    code: 'BRANCH_COMPANY',
    name: '지사 사업장',
    masterCode: 'COMPANY_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '',
  },
  {
    code: 'BUYER_COMPANY',
    name: '매출 거래처',
    masterCode: 'COMPANY_TYPE',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '',
  },
  {
    code: 'SELLER_COMPANY',
    name: '매입 거래처',
    masterCode: 'COMPANY_TYPE',
    level: 1,
    type: 'system',
    orderby: 4,
    description: '',
  },
  // 창고 유형(STORAGE_TYPE)
  {
    code: 'STORAGE_TYPE',
    name: '창고 유형',
    masterCode: 'STORAGE_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'STORAGE_INFLOW',
    name: '저장 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '모든 자재, 제품, 반제품을 저장하는 용도로 사용',
  },
  {
    code: 'STORAGE_PREEMPTATION',
    name: '선점 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '생산창고로 이동전 미리 생산에 대한 자재 선점을 위한 창고',
  },
  {
    code: 'STORAGE_PRODUCTION',
    name: '생산 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '생산시 해당 자재를 옮겨서 재고 관리에 사용함',
  },
  {
    code: 'STORAGE_OUTFLOW',
    name: '출고 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '출고를 위해 (미리) 상품을 빼 놓는 방식으로 사용함',
  },
  {
    code: 'STORAGE_TEMPORARY',
    name: '임시 보관',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 4,
    description: '정식 재고로 잡지 않을 용도의 창고(예: 가입고)',
  },
  {
    code: 'STORAGE_OUTSOURCING',
    name: '외주 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 5,
    description: '외주업체의 창고로 사용함',
  },
  {
    code: 'STORAGE_FAULTY',
    name: '불량 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 6,
    description: '',
  },
  {
    code: 'STORAGE_DISUSE',
    name: '불용 창고',
    masterCode: 'STORAGE_TYPE',
    level: 1,
    type: 'system',
    orderby: 7,
    description: '',
  },
  // 품목 계정(ITEM_GROUP)
  {
    code: 'ITEM_GROUP',
    name: '품목 계정',
    masterCode: 'ITEM_GROUP',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'MATERIAL',
    name: '재료',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '부품으로 변환할 수 있는 리소스(가공이 필요한 원재료)',
  },
  {
    code: 'PART',
    name: '부품',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '제품 구조를 만들기 위한 부품 혹은 반제품',
  },
  {
    code: 'PRODUCT',
    name: '완제품',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '제품 판매를 위한 완제품',
  },
  {
    code: 'WORK',
    name: '작업',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 4,
    description: '생산 활동에 필요한 작업',
  },
  {
    code: 'ENGINEERING_CHANGE',
    name: '엔지니어링 변경',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 5,
    description: '',
  },
  {
    code: 'PSEUDO',
    name: 'Pseudo 부품',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 6,
    description: '실제적으로 조립되지 않으나 생산에 함께 투입되는 부품을 가상으로 묶음',
  },
  {
    code: 'PHANTOM',
    name: 'Phantom 부품',
    masterCode: 'ITEM_GROUP',
    level: 1,
    type: 'system',
    orderby: 7,
    description: '물리적으로 조립되는 부품이지만 공정중에 짧게 나타나서 재고관리를 하지 않는 부품',
  },
  // 품목 형태(ITEM_TYPE)
  {
    code: 'ITEM_TYPE',
    name: '품목 형태',
    masterCode: 'ITEM_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'ITEM_FABRIC',
    name: '원단',
    masterCode: 'ITEM_TYPE',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'ITEM_WIRE',
    name: '와이어',
    masterCode: 'ITEM_TYPE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'ITEM_FILTER',
    name: '필터',
    masterCode: 'ITEM_TYPE',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  {
    code: 'ITEM_ETC',
    name: '기타',
    masterCode: 'ITEM_TYPE',
    level: 1,
    type: 'company',
    orderby: 5,
    description: '',
  },
  // 품목 단위(ITEM_UNIT)
  {
    code: 'ITEM_UNIT',
    name: '품목 단위',
    masterCode: 'ITEM_UNIT',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  { code: 'UNIT_EA', name: 'EA', masterCode: 'ITEM_UNIT', level: 1, type: 'company', orderby: 1, description: '' },
  { code: 'UNIT_BOX', name: '박스', masterCode: 'ITEM_UNIT', level: 1, type: 'company', orderby: 2, description: '' },
  { code: 'UNIT_ROLL', name: '롤', masterCode: 'ITEM_UNIT', level: 1, type: 'company', orderby: 3, description: '' },
  { code: 'UNIT_METER', name: '미터', masterCode: 'ITEM_UNIT', level: 1, type: 'company', orderby: 4, description: '' },
  { code: 'UNIT_KG', name: 'kg', masterCode: 'ITEM_UNIT', level: 1, type: 'company', orderby: 5, description: '' },
  // 포장 단위(PACKING_UNIT)
  {
    code: 'PACKING_UNIT',
    name: '포장 단위',
    masterCode: 'PACKING_UNIT',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'PACKING_BOX',
    name: '박스',
    masterCode: 'PACKING_UNIT',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'PACKING_ROLL',
    name: '롤',
    masterCode: 'PACKING_UNIT',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  // 과세 유형(TAX_TYPE)
  {
    code: 'TAX_TYPE',
    name: '과세 유형',
    masterCode: 'TAX_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'VAT_INCLUDE',
    name: '부가세 포함',
    masterCode: 'TAX_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '',
  },
  {
    code: 'VAT_EXCLUDE',
    name: '부가세 별도',
    masterCode: 'TAX_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '',
  },
  { code: 'DUTY_FREE', name: '면세', masterCode: 'TAX_TYPE', level: 1, type: 'system', orderby: 3, description: '' },
  // 검사 유형(INSPECTION_TYPE)
  {
    code: 'INSPECTION_TYPE',
    name: '검사 유형',
    masterCode: 'INSPECTION_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'INSPECTION_ALL',
    name: '전수 검사',
    masterCode: 'INSPECTION_TYPE',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'INSPECTION_SAMPLE',
    name: '샘플 검사',
    masterCode: 'INSPECTION_TYPE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  // 검사 방법(INSPECTION_METHOD)
  {
    code: 'INSPECTION_METHOD',
    name: '검사 방법',
    masterCode: 'INSPECTION_METHOD',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'INSPECTION_VISION',
    name: '비전검사',
    masterCode: 'INSPECTION_METHOD',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'INSPECTION_SENSORY',
    name: '관능검사',
    masterCode: 'INSPECTION_METHOD',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'INSPECTION_FUNCTION',
    name: '기능검사',
    masterCode: 'INSPECTION_METHOD',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  // 품질검사유형
  {
    code: 'QUALITY_CHECK_TYPE',
    name: '품질검사유형',
    masterCode: 'QUALITY_CHECK_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'QUALITY_CHECK_VISUAL',
    name: '외관 검사',
    masterCode: 'QUALITY_CHECK_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '외관 검사',
  },
  {
    code: 'QUALITY_CHECK_FUNCTIONAL',
    name: '기능 검사',
    masterCode: 'QUALITY_CHECK_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '기능 검사',
  },
  // 반품 종류(RETURN_TYPE)
  {
    code: 'RETURN_TYPE',
    name: '반품 종류',
    masterCode: 'RETURN_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'RETURN_REPLACEMENT',
    name: '교환',
    masterCode: 'RETURN_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '교환하는 경우',
  },
  {
    code: 'RETURN_REFUND',
    name: '환불',
    masterCode: 'RETURN_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '금액을 환불 받는 경우',
  },
  {
    code: 'RETURN_DESTROY',
    name: '폐기',
    masterCode: 'RETURN_TYPE',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '자체로 폐기하는 경우',
  },
  // 불량 타입(NG_TYPE)
  { code: 'NG_TYPE', name: '불량 종류', masterCode: 'NG_TYPE', level: 0, type: 'system', orderby: 0, description: '' },
  { code: 'NG_TYPE1', name: '이물질', masterCode: 'NG_TYPE', level: 1, type: 'company', orderby: 1, description: '' },
  {
    code: 'NG_TYPE2',
    name: '노즈/융착 불량',
    masterCode: 'NG_TYPE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'NG_TYPE3',
    name: '귀끈 불량',
    masterCode: 'NG_TYPE',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  {
    code: 'NG_TYPE4',
    name: '커팅 불량',
    masterCode: 'NG_TYPE',
    level: 1,
    type: 'company',
    orderby: 4,
    description: '',
  },
  // 입/출고 유형(INVENTORY_TYPE)
  {
    code: 'INVENTORY_TYPE',
    name: '입/출고 유형',
    masterCode: 'INVENTORY_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '모든 품목의 재고를 관리하기 위한 입/출고 유형',
  },
  {
    code: 'MATERIAL_IN',
    name: '자재 입고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '자재나 부품을 구매하여 입고하는 경우(가입고 포함)',
  },
  {
    code: 'PRODUCT_OUT',
    name: '상품 출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '완제품을 정식으로 판매하기 위한 출고의 경우',
  },
  {
    code: 'PRODUCT_CANCEL',
    name: '출고취소 입고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '출고가 취소되어 다시 입고하는 경우',
  },
  {
    code: 'STORAGE_MOVE',
    name: '창고이동 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 4,
    description: '단순히 창고의 품목을 이동한는 경우(수입검사 포함)',
  },
  {
    code: 'PRODUCTION_ACTIVITY',
    name: '생산활동 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 5,
    description: '생산활동을 입/출고 하는 경우',
  },
  {
    code: 'OUTSOURCING',
    name: '외주활동 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 6,
    description: '외주를 입/출고 하는 경우',
  },
  {
    code: 'QUALITY_CHECK_INVENTORY',
    name: '품질검사 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 7,
    description: '품질검사를 위해 입/출고 하는 경우',
  },
  {
    code: 'RETURN_OUT',
    name: '반품처리 출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 8,
    description: '자재나 부품의 불량으로 인해 반품 처리를 위해 출고하는 경우',
  },
  {
    code: 'RETURN_IN',
    name: '반품처리 입고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 9,
    description: '구매자의 변심, 불량으로 인해 반품 처리를 위해 입고하는 경우',
  },
  {
    code: 'CORRECT_INVENTORY',
    name: '재고보정 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 10,
    description: '재고 데이터를 맞추기 위해 보정하는 경우',
  },
  {
    code: 'DEFECTIVE_INVENTORY',
    name: '불량 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 11,
    description: '자재나 부품의 불량을 등록하는 경우',
  },
  {
    code: 'USELESS_INVENTORY',
    name: '불용 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 12,
    description: '자재나 부품의 불용을 등록하는 경우',
  },
  {
    code: 'LOST_OUT',
    name: '망실 처리',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 13,
    description: '자재나 부품의 망실을 등록하여 감소처리 하는 경우',
  },
  {
    code: 'DISPOSAL_OUT',
    name: '폐기 처리',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 14,
    description: '자재나 부품의 폐기를 등록하여 감소처리 하는 경우',
  },
  {
    code: 'SURPLUS_IN',
    name: '잉여 입고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 15,
    description: '자재나 부품의 잉여를 등록하는 경우',
  },
  {
    code: 'REVERSAL_INVENTORY',
    name: '환입 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 16,
    description: '자재나 부품의 환입을 등록하는 경우',
  },
  {
    code: 'DISMANTLE_IN',
    name: '해체 입고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 17,
    description: '완제품 or 반제품을 해체하여 생긴 부품or자재를 입고 등록하는 경우',
  },
  {
    code: 'AS_INVENTORY',
    name: 'AS 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 18,
    description: '제품이 AS로 입고/출고되는 경우',
  },
  {
    code: 'PREEMPTATION_INVENTORY',
    name: '선점 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 18,
    description: '생산을 위한 자재를 미리 선점하는 용도',
  },
  {
    code: 'PALLET_DISMANTLE_INVENTORY',
    name: '파레트 해체 입/출고',
    masterCode: 'INVENTORY_TYPE',
    level: 1,
    type: 'system',
    orderby: 19,
    description: '파레트를 해체해 파레트 바코드를 출고하고 롤별 바코드를 입고하는 경우',
  },

  // 설비타입(FACILITY_TYPE)
  {
    code: 'FACILITY_TYPE',
    name: '설비타입',
    masterCode: 'FACILITY_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'FAC_MASK_MAKER',
    name: '마스크 생산기',
    masterCode: 'FACILITY_TYPE',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'FAC_MASK_VISION',
    name: '비전 마스크 생산기',
    masterCode: 'FACILITY_TYPE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  // 설비중단사유(INTERRUPT_REASON)
  {
    code: 'INTERRUPT_REASON',
    name: '설비 중단 사유',
    masterCode: 'INTERRUPT_REASON',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'MATERIAL_REPLACEMENT',
    name: '재료 교체',
    masterCode: 'INTERRUPT_REASON',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '',
  },
  {
    code: 'PARTS_REPLACEMENT',
    name: '부품 교체',
    masterCode: 'INTERRUPT_REASON',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '',
  },
  {
    code: 'FACILITY_CHECK',
    name: '장비 점검',
    masterCode: 'INTERRUPT_REASON',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '',
  },
  {
    code: 'FACILITY_BREAK',
    name: '장비 휴식',
    masterCode: 'INTERRUPT_REASON',
    level: 1,
    type: 'system',
    orderby: 4,
    description: '',
  },
  {
    code: 'FACILITY_FAILUER',
    name: '장비 고장',
    masterCode: 'INTERRUPT_REASON',
    level: 1,
    type: 'system',
    orderby: 5,
    description: '',
  },
  {
    code: 'PRODUCT_NG',
    name: '제품 불량 발생',
    masterCode: 'INTERRUPT_REASON',
    level: 1,
    type: 'system',
    orderby: 6,
    description: '',
  },
  // 설비 점검 주기(MAINTENANCE_CYCLE)
  {
    code: 'MAINTENANCE_CYCLE',
    name: '설비 점검 주기',
    masterCode: 'MAINTENANCE_CYCLE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'MAINTENANCE_DAILY',
    name: '일일점검',
    masterCode: 'MAINTENANCE_CYCLE',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'MAINTENANCE_WEEKLY',
    name: '주간점검',
    masterCode: 'MAINTENANCE_CYCLE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'MAINTENANCE_MONTHLY',
    name: '월간점검',
    masterCode: 'MAINTENANCE_CYCLE',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  {
    code: 'MAINTENANCE_QUARTERLY',
    name: '분기점검',
    masterCode: 'MAINTENANCE_CYCLE',
    level: 1,
    type: 'company',
    orderby: 4,
    description: '',
  },
  {
    code: 'MAINTENANCE_YEARLY',
    name: '연간점검',
    masterCode: 'MAINTENANCE_CYCLE',
    level: 1,
    type: 'company',
    orderby: 5,
    description: '',
  },
  // 설비점검결과(MAINTENANCE_RESULT)
  {
    code: 'MAINTENANCE_RESULT',
    name: '설비 점검 결과',
    masterCode: 'MAINTENANCE_RESULT',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'MAINTENANCE_OK',
    name: '정상',
    masterCode: 'MAINTENANCE_RESULT',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'MAINTENANCE_NG',
    name: '비정상',
    masterCode: 'MAINTENANCE_RESULT',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  // 포장 타입(PACKAGE_TYPE)
  {
    code: 'PACKAGE_TYPE',
    name: '포장 타입',
    masterCode: 'PACKAGE_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'PACKAGE_INBOX',
    name: 'INBOX',
    masterCode: 'PACKAGE_TYPE',
    level: 1,
    type: 'company',
    orderby: 1,
    description: '',
  },
  {
    code: 'PACKAGE_OUTBOX',
    name: 'OUTBOX',
    masterCode: 'PACKAGE_TYPE',
    level: 1,
    type: 'company',
    orderby: 2,
    description: '',
  },
  {
    code: 'PACKAGE_PALLET',
    name: 'PALLET',
    masterCode: 'PACKAGE_TYPE',
    level: 1,
    type: 'company',
    orderby: 3,
    description: '',
  },
  // 처리 유형(ACTION_TYPE) 입력, 수정, 삭제
  {
    code: 'ACTION_TYPE',
    name: 'BOM 처리 유형',
    masterCode: 'ACTION_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'ACTION_TYPE_INSERT',
    name: '등록',
    masterCode: 'ACTION_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '',
  },
  {
    code: 'ACTION_TYPE_UPDATE',
    name: '수정',
    masterCode: 'ACTION_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: '',
  },
  {
    code: 'ACTION_TYPE_DELETE',
    name: '삭제',
    masterCode: 'ACTION_TYPE',
    level: 1,
    type: 'system',
    orderby: 3,
    description: '',
  },
  // 출고요청 유형(OUTFLOW_TYPE)
  {
    code: 'OUTFLOW_TYPE',
    name: '출고요청 유형',
    masterCode: 'OUTFLOW_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'OUTFLOW_WORK',
    name: '생산지시 출고요청',
    masterCode: 'OUTFLOW_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: '생산으로 인한 자재 출고요청',
  },
  {
    code: 'OUTFLOW_AS',
    name: 'AS 출고요청',
    masterCode: 'OUTFLOW_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: 'AS로 인한 자재 출고 요청',
  },
  // AS 요청유형
  {
    code: 'AS_REQUEST_TYPE',
    name: 'AS 요청유형',
    masterCode: 'AS_REQUEST_TYPE',
    level: 0,
    type: 'system',
    orderby: 0,
    description: '',
  },
  {
    code: 'AS_REPAIR',
    name: '수리',
    masterCode: 'AS_REQUEST_TYPE',
    level: 1,
    type: 'system',
    orderby: 1,
    description: 'AS 수리',
  },
  {
    code: 'AS_CORRECT',
    name: '교정',
    masterCode: 'AS_REQUEST_TYPE',
    level: 1,
    type: 'system',
    orderby: 2,
    description: 'AS 교정',
  },
];

// 기본 사업장
export const initCompany = {
  name: '마스터 사업장',
  code: 'master',
};

// 기본 권한 그룹
export const initRoleGroups = [
  {
    code: 'staff',
    name: '일반 사용자',
    type: 'system',
    description: '일반 사용자',
  },
  /*
  {
    code: 'request_confirm',
    name: '구매 승인자',
    type: 'system',
    description: '구매 승인자',
  },
  {
    code: 'purchase_confirm',
    name: '발주 승인자',
    type: 'system',
    description: '발주 승인자',
  },
  {
    code: 'receive_confirm',
    name: '입고 승인자',
    type: 'system',
    description: '입고 승인자',
  },
  {
    code: 'quotation_confirm',
    name: '견적 승인자',
    type: 'system',
    description: '견적 승인자',
  },
  {
    code: 'release_confirm',
    name: '출고 승인자',
    type: 'system',
    description: '출고 승인자',
  },
  */
  {
    code: 'task_manager',
    name: '생산 관리자',
    type: 'system',
    description: '생산 관리자',
  },
  {
    code: 'production_manager',
    name: '작업 관리자',
    type: 'system',
    description: '작업 관리자',
  },
];
